//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhaptics.SDK2
{
    using System;
    using UnityEngine;
    
    
    public class BhapticsEvent
    {
        
        public const string TOUCH_CATCHABLE_RIGHT = "touch_catchable_right";
        
        public const string GAME_START = "game_start";
        
        public const string CORRECT_LEFT = "correct_left";
        
        public const string WRONG_LEFT = "wrong_left";
        
        public const string WRONG_RIGHT = "wrong_right";
        
        public const string WRONG_BOTH = "wrong_both";
        
        public const string CORRECT_BOTH = "correct_both";
        
        public const string CORRECT_RIGHT = "correct_right";
        
        public const string TOUCH_CATCHABLE_LEFT = "touch_catchable_left";
    }
}
